/*
 * File Name: STD_MACROS.h
 * Creation Date: 07/20/2020
 * Author: Rehab
 * Description: Header File for standard macros....
 */ 

#ifndef STD_MACROS_H_
#define STD_MACROS_H_

/*****************************************************GENERAL MACROS*************************************************/
//GENERAL MACROS
#define LOW 0
#define HIGH 1

#define BIT_LOW 0
#define TWO_BITS_LOW 0
#define THREE_BITS_LOW 0
#define FOUR_BITS_LOW 0
#define FIVE_BITS_LOW 0
#define SIX_BITS_LOW 0
#define SEVEN_BITS_LOW 0
#define EIGHT_BITS_LOW 0

#define LOWER_NIBBLE_LOW 0
#define HIGHER_NIBBLE_LOW 0
#define PORT_LOW 0
#define NIBBLE_LOW 0

#define BIT_HIGH 1
#define TWO_BITS_HIGH 3
#define THREE_BITS_HIGH 7
#define FOUR_BITS_HIGH 15
#define FIVE_BITS_HIGH 31
#define SIX_BITS_HIGH 63
#define SEVEN_BITS_HIGH 127
#define EIGHT_BITS_HIGH 255

#define LOWER_NIBBLE_HIGH 65535U
#define HIGHER_NIBBLE_HIGH 65535U
//#define PORT_HIGH 255
#define NIBBLE_HIGH 15

#define LOWER_NIBBLE 0
#define HIGHER_NIBBLE 16

#define NIBBLE_ZERO 0
#define NIBBLE_ONE 1
#define NIBBLE_TWO 2
#define NIBBLE_THREE 3
#define NIBBLE_FOUR 4
#define NIBBLE_FIVE 5
#define NIBBLE_SIX 6
#define NIBBLE_SEVEN 7


/********************************************************************************************************************/

/**************************************************MACROS_LIKE_FUNCTIONS*********************************************/
//MACROS_LIKE_FUNCTIONS
#define BIT_WRITE(REG,BITNO,VAL) REG=(REG&(~(BIT_HIGH<<BITNO)))|(VAL<<BITNO)
#define TWO_BITS_WRITE(REG,FIRSTBITNO,VAL) REG=(REG&(~(TWO_BITS_HIGH<<FIRSTBITNO)))|(VAL<<FIRSTBITNO)
#define THREE_BITS_WRITE(REG,FIRSTBITNO,VAL) REG=(REG&(~(THREE_BITS_HIGH<<FIRSTBITNO)))|(VAL<<FIRSTBITNO)
#define FOUR_BITS_WRITE(REG,FIRSTBITNO,VAL) REG=(REG&(~(FOUR_BITS_HIGH<<FIRSTBITNO)))|(VAL<<FIRSTBITNO)
#define FIVE_BITS_WRITE(REG,FIRSTBITNO,VAL) REG=(REG&(~(FIVE_BITS_HIGH<<FIRSTBITNO)))|(VAL<<FIRSTBITNO)
#define SIX_BITS_WRITE(REG,FIRSTBITNO,VAL) REG=(REG&(~(SIX_BITS_HIGH<<FIRSTBITNO)))|(VAL<<FIRSTBITNO)
#define SEVEN_BITS_WRITE(REG,FIRSTBITNO,VAL) REG=(REG&(~(SEVEN_BITS_HIGH<<FIRSTBITNO)))|(VAL<<FIRSTBITNO)
#define EIGHT_BITS_WRITE(REG,FIRSTBITNO,VAL) REG=(REG&(~(EIGHT_BITS_HIGH<<FIRSTBITNO)))|(VAL<<FIRSTBITNO)

//#define HIGHER_NIBBLE_WRITE(REG,VAL) REG=(REG&0x0F)|(VAL<<4)
#define HIGHER_NIBBLE_WRITE(REG,VAL) REG=(REG&(~(HIGHER_NIBBLE_HIGH<<HIGHER_NIBBLE)))|(VAL<<HIGHER_NIBBLE)
//#define LOWER_NIBBLE_WRITE(REG,VAL) REG=(REG&0xF0)|VAL
#define LOWER_NIBBLE_WRITE(REG,VAL) REG=(REG&(~(LOWER_NIBBLE_HIGH<<LOWER_NIBBLE)))|(VAL<<LOWER_NIBBLE)
#define NIBBLE_WRITE(REG,NIBBLENO,VAL)	REG=(REG&(~(NIBBLE_HIGH<<((NIBBLENO)*4))))|(VAL<<((NIBBLENO)*4))
#define REG_WRITE(REG,VAL) REG=VAL

//BIT_GET TO KNOW THE VALUE OF THE BIT
#define BIT_GET(REG,BITNO) ((REG>>BITNO)&BIT_HIGH)
#define TWO_BITS_GET(REG,FIRSTBITNO) ((REG>>FIRSTBITNO)&TWO_BITS_HIGH)
//HIGHER_NIBBLE_GET TO KNOW THE VALUE IN THE HIGHER NIBBLE 
#define HIGHER_NIBBLE_GET(REG) ((REG>>HIGHER_NIBBLE)&(HIGHER_NIBBLE_HIGH))
//LOWER_NIBBLE_GET TO KNOW THE VALUE IN THE LOWER NIBBLE 
#define LOWER_NIBBLE_GET(REG) ((REG>>LOWER_NIBBLE)&(LOWER_NIBBLE_HIGH))
//REG_GET TO KNOW THE VALUE IN THE REGISTER 
#define REG_GET(REG) (REG)
#define NIBBLE_GET(REG,NIBBLENO) ((REG>>((NIBBLENO)*4))&(NIBBLE_HIGH))

#define BIT_TOGGLE(REG,BITNO) REG^=(BIT_HIGH<<BITNO)
#define HIGHER_NIBBLE_TOGGLE(REG) REG^=(HIGHER_NIBBLE_HIGH<<HIGHER_NIBBLE)
#define LOWER_NIBBLE_TOGGLE(REG) REG^=(LOWER_NIBBLE_HIGH<<LOWER_NIBBLE)
#define REG_TOGGLE(REG) REG=~REG
#define NIBBLE_TOGGLE(REG,NIBBLENO) REG^=(NIBBLE_HIGH<<((NIBBLENO)*4))
/********************************************************************************************************************/ 
#endif
